FROM golang:1.20-alpine

WORKDIR /app
COPY . .

# Install required tools
RUN apk add --no-cache bash git

# Build the binary
RUN GOOS=linux GOARCH=amd64 go build -o manager main.go

# Use Alpine as minimal base image
FROM alpine:3.18

WORKDIR /
COPY --from=0 /app/manager .
COPY --from=0 /app/config /config

# Set up a non-root user
RUN addgroup -S sdcore && adduser -S sdcore -G sdcore
USER sdcore

ENTRYPOINT ["/manager"]
