apiVersion: v1
kind: Namespace
metadata:
  name: sdcore-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdcore-operator
  namespace: sdcore-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdcore-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "events"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["workload.nephio.org"]
  resources: ["nfdeployments", "nfdeployments/status"]
  verbs: ["*"]
- apiGroups: ["ref.nephio.org"]
  resources: ["configs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["network-attachment-definitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdcore-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sdcore-operator
subjects:
- kind: ServiceAccount
  name: sdcore-operator
  namespace: sdcore-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdcore-operator
  namespace: sdcore-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdcore-operator
  template:
    metadata:
      labels:
        app: sdcore-operator
    spec:
      serviceAccountName: sdcore-operator
      containers:
      - name: manager
        image: sdcore-operator:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi" 