apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nfdeployments.workload.nephio.org
spec:
  group: workload.nephio.org
  names:
    kind: NFDeployment
    listKind: NFDeploymentList
    plural: nfdeployments
    singular: nfdeployment
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                provider:
                  type: string
                  description: Specifies the network function provider, e.g., upf.sdcore.io, amf.sdcore.io, etc.
                interfaces:
                  type: array
                  description: Network interfaces configuration for the NF
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Interface name
                      ipv4:
                        type: object
                        properties:
                          address:
                            type: string
                            description: IPv4 address with CIDR
                          gateway:
                            type: string
                            description: IPv4 gateway address
                parameterValues:
                  type: array
                  description: Array of parameter key-value pairs for NF configuration
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Parameter name
                      value:
                        type: string
                        description: Parameter value
                monitoringEnabled:
                  type: boolean
                  description: Whether monitoring is enabled for this NF
                replicas:
                  type: integer
                  description: Number of replicas for the NF deployment
                upstreamNFs:
                  type: array
                  description: List of upstream network functions that this NF depends on
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The type of the upstream NF (e.g., AMF, SMF, NRF)
                      name:
                        type: string
                        description: The name of the upstream NF
                      namespace:
                        type: string
                        description: The namespace of the upstream NF
          required:
            - spec
      subresources:
        status: {} 