apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdcore-operator
  namespace: sdcore-system
  labels:
    app: sdcore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdcore-operator
  template:
    metadata:
      labels:
        app: sdcore-operator
    spec:
      serviceAccountName: sdcore-operator
      containers:
      - name: manager
        image: docker.io/nephio/sdcore-operator:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10 